blog_app/urls.py
from django.urls import path
from . import views

app_name='blog_app'

urlpatterns = [

    path('post_list/',views.PostListView.as_view(),name='post_lists'),
    path('post_details/<int:pk>/',views.PostDetailView.as_view(),name='post_details'),
    path('post/new',views.PostCreateView.as_view(),name='post_create'),
    path('post_drafts_list',views.PostDraftView.as_view(),name='post_drafts_list'),
    path('post_drafts_details/<int:pk>/',views.PostDraftDetailsView.as_view(),name='post_drafts_details'),
    path('post_publish/<int:pk>/publish',views.post_publish,name='post_publish'),
    path('post_comment/<int:pk>/add_comment',views.add_comment,name='add_comment'),
    path('post_update/<int:pk>/',views.PostUpdateView.as_view(),name='post_update'),
    path('post_delete/<int:pk>/',views.PostdeleteView.as_view(),name='post_delete'),
    path('comment_update/<int:pk>/',views.CommentUpdateView.as_view(),name='comment_update'),
    path('comment_remove/<int:pk>/',views.CommentRemoveView.as_view(),name='comment_delete')
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Index.as_view(),name='index'),
    path('user_accounts_app/',include('user_accounts_app.urls')),
    path('blog_app/',include('blog_app.urls')),
    # path('welcome/',views.Welcome.as_view(),name='welcome'), replaced it with index page in setting.py
    path('thanks/',views.Thanks.as_view(),name='thanks'),
    path('session_security/', include('session_security.urls')),
    path('accounts/',include('allauth.urls')),
    #path('captcha/',include('captcha.urls')),
]

user_accounts_app/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.views import generic

app_name='user_accounts_app'

urlpatterns = [
    path('sign_up/',views.SignUp.as_view(),name='signup'),
    path('sign_in/',auth_views.LoginView.as_view(template_name='user_accounts_app/sign_in.html'),name='signin'),
    path('sign_out/',auth_views.LogoutView.as_view(),name='signout'),
    path('change_password',auth_views.PasswordChangeView.as_view(template_name='user_accounts_app/change_password.html'
                                                                 ,success_url=reverse_lazy('user_accounts_app:signin')),
         name='change_password'),

]

blog_app/models.py
from django.contrib.auth import get_user_model
from django.db import models
from crum import get_current_user

# Create your models here.
from django.urls import reverse
from django.utils import timezone

User=get_user_model()

class Post(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,default=None)
    title = models.CharField(max_length=150)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog_app:post_details',kwargs={'pk':self.pk})

    def save(self,*args,**kwargs):
        current_user=get_current_user()
        if current_user and not User.pk:
            current_user=None
        if not self.pk:
            self.author=current_user
        super(Post,self).save(*args,**kwargs)

    def publish(self):
        self.published_date=timezone.now()
        self.save()


class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,blank=True,null=True,related_name='comments')
    ##this related name is used in templates
    text=models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    created_by=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True,default=None)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('blog_app:post_details',kwargs={'pk':self.pk})

    def save(self,*args,**kwargs):
        current_user=get_current_user()
        if current_user and not User.pk:
            current_user=None
        if not self.pk:
            self.created_by=current_user
        super(Comment,self).save(*args,**kwargs)

user_accounts_app/models.py
from django.contrib import auth
from django.db import models



# Create your models here.

class UserAccount(auth.models.User,auth.models.PermissionsMixin):


    def __str__(self):
        return "@{}".format(self.username)

blog_app/forms.py
from django import forms
from . import models

class PostForm(forms.ModelForm):
    class Meta():
        model=models.Post
        fields=('title','text')

class CommentForm(forms.ModelForm):
    class Meta():
        model=models.Comment
        fields=('text',)

user_accounts_app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields=('username','email','password1','password2')

        model=get_user_model()

blog_app/views.py
from django.contrib.auth import mixins
from django.contrib.auth import decorators
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils import timezone

from django.views import generic
from . import models
from . import forms


class PostListView(generic.ListView):
    model = models.Post
    template_name = 'blog_app/post_lists.html'

    def get_queryset(self):
        return models.Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(generic.DetailView):
    model = models.Post
    template_name = 'blog_app/post_details.html'


class PostCreateView(generic.CreateView,mixins.LoginRequiredMixin):
    model = models.Post
    template_name = 'blog_app/post_create.html'
    form_class = forms.PostForm


class PostDraftView(generic.ListView):
    model=models.Post
    template_name = 'blog_app/post_drafts.html'

    def get_queryset(self):
        return models.Post.objects.filter(author=self.request.user).order_by('-created_date')



class PostDraftDetailsView(generic.DetailView):
    model = models.Post
    template_name = 'blog_app/post_draft_details.html'


@decorators.login_required
def post_publish(request,pk):
    post=get_object_or_404(models.Post,pk=pk)
    post.publish()
    return redirect('blog_app:post_details',pk=pk)

@decorators.login_required
def add_comment(request,pk):
    post_name=get_object_or_404(models.Post,pk=pk)
    if request.method=='POST':
        form=forms.CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post_name
            comment.save()
            return redirect('blog_app:post_details',pk=post_name.pk)
    else:
        form=forms.CommentForm
        return render(request, 'blog_app/add_comment.html', {'form': form})  #this if for the GET request to return form


class PostUpdateView(mixins.LoginRequiredMixin,generic.UpdateView):
    model = models.Post
    template_name = 'blog_app/post_update.html'
    form_class = forms.PostForm
    #redirect_field_name = 'blog_app/post_details.html'

class PostdeleteView(mixins.LoginRequiredMixin,generic.DeleteView):
    model = models.Post
    template_name = 'blog_app/post_delete.html'
    success_url = reverse_lazy('blog_app:post_lists')


class CommentUpdateView(mixins.LoginRequiredMixin,generic.UpdateView):
    model = models.Comment
    template_name = 'blog_app/comment_update.html'
    form_class = forms.CommentForm
    success_url = reverse_lazy('blog_app:post_lists')

class CommentRemoveView(mixins.LoginRequiredMixin,generic.DeleteView):
    model = models.Comment
    template_name = 'blog_app/comment_delete.html'
    success_url = reverse_lazy('blog_app:post_lists')

# @decorators.login_required
# def CommentRemoveView(request,pk):
#     comment=get_object_or_404(models.Comment,pk)
#     post_pk=comment.post.pk
#     comment.delete()
#     return  redirect('blog_app:post_details',post_pk)

blog_project/views.py
from django.views import generic


class Index(generic.TemplateView):
    template_name = 'index.html'

class Welcome(generic.TemplateView):
    template_name = 'welcome.html'

class Thanks(generic.TemplateView):
    template_name = 'thanks.html'

user_accounts_app/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views import generic

from . import forms

from django.contrib.auth import views as auth_views




class SignUp(generic.CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('user_accounts_app:signin')
    template_name = 'user_accounts_app/sign_up.html'
    

blog_app/templates/blog_app/add_comment.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
    <h1>Add comment</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add comment</button>
    </form>
</div>
{% endblock %}

blog_app/templates/blog_app/comment_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
    <form method="POST">
        {% csrf_token %}
        <h2>Are you sure you want to delete comment "{{ object }}" ?</h2>
        <input class="btn btn-danger" type="submit" value="Confirm">
        <a class="btn btn-primary"  href="{% url 'blog_app:post_lists' %}">Cancel</a>
    </form>
        </div>
{% endblock %}

blog_app/templates/blog_app/comment_update.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
    <h1>Update comment</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Update</button>
    </form>
    </div>

{% endblock %}

blog_app/templates/blog_app/post_create.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <div class="jumbotron">
    <h1>Create Blog</h1>
    <form method="POST">
        {% csrf_token %}
          {{ form.as_p }}

        <button type="submit" class="save btn btn-primary">Save</button>
    </form>

            <script src="{% static 'blog_app/js/medium-editor.js' %}"></script>
        </div>



{% endblock %}

blog_app/templates/blog_app/post_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
    <form method="POST">
        {% csrf_token %}
        <h2>Are you sure you want to delete blog "{{ object }}" ?</h2>
        <input class="btn btn-danger" type="submit" value="Confirm">
        <a class="btn btn-primary"  href="{% url 'blog_app:post_details' pk=post.pk %}">Cancel</a>
    </form>
    </div>
{% endblock %}

blog_app/templates/blog_app/post_details.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <div class="jumbotron">
    <h1>{{ post.title }}</h1>
    {% if post.published_date %}
        <div><h6>Published on {{ post.published_date }}</h6></div>
        <h6>Posted by {{ post.author }}</h6>
        <p>{{ post.text }}</p>
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'blog_app:add_comment' pk=post.pk %}">Add comment</a>
            {% if post.author == user %}
                <a class="btn btn-primary" href="{% url 'blog_app:post_update' pk=post.pk %}">Update Blog</a>
                <a class="btn btn-primary" href="{% url 'blog_app:post_delete' pk=post.pk %}">Delete Blog</a>
            {% endif %}
        {% endif %}
        <p><strong>{{ post.comments.count }} comments</strong></p>
        {% for i in post.comments.all %}
<!--            'comments' comes from related name of models foregin key-->
                <p><strong>{{ i.created_by }}</strong> at {{ i.created_date }}</p>
                <p>{{ i.text|safe|linebreaks }}
                {% if i.created_by == user %}
                    <a class="btn btn-info" href="{% url 'blog_app:comment_update' pk=i.pk %}">
                        update comment</a>
                    <a class="btn btn-info" href="{% url 'blog_app:comment_delete' pk=i.pk %}">
                        Delete comment </a>
                {% endif %} </p>
<!--                <p>-->
<!--                    {% if i.post.author == user %}-->
<!--                    <a class="btn btn-info" href="{% url 'blog_app:comment_delete' pk=i.pk %}">-->
<!--                        Delete comment</a>-->
<!--                {% endif %} </p>-->

        {% endfor %}
    {% else %}
        <h6>Posted by {{ post.author }}</h6>
        <h6>Not published</h6>
        <p>{{ post.text }}</p>
         <a class="btn btn-primary" href="{% url 'blog_app:post_publish' pk=post.pk %}">Publish</a>
        <a class="btn btn-primary" href="{% url 'blog_app:post_update' pk=post.pk %}">Update Blog</a>
    </div>
    {% endif %}
<!--        <script src="{% static 'blog_app/js/medium-editor.js' %}"></script>-->
{% endblock %}

blog_app/templates/blog_app/post_draft_details.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
        <h1>{{ post.title }}</h1>
        <h6>Posted by {{ post.author }}</h6>
        <h6>Created on: {{ post.created_date }}</h6>
        <p>{{ post.text }}</p>
        <h6>Not published</h6>
        <a class="btn btn-primary" href="{% url 'blog_app:post_publish' pk=post.pk %}">Publish</a>
        <a class="btn btn-primary" href="{% url 'blog_app:post_update' pk=post.pk %}">Update Blog</a>
        <a class="btn btn-primary" href="{% url 'blog_app:post_delete' pk=post.pk %}">Delete Blog</a>
    </div>
{% endblock %}

blog_app/templates/blog_app/post_drafts.html
{% extends 'base.html' %}
{% block content %}
  <div class="jumbotron">
      <h1><strong>Draft</strong></h1>
      {% for i in post_list %}
      <!--    post_list comes from name of model in small letter + '_list'-->
      {% if not i.published_date%}
      <div>
          <h1><a href="{% url 'blog_app:post_drafts_details' pk=i.pk %}">{{ i.title }}</a> </h1>
      </div>
          <p>Created on {{ i.created_date }}</p>
          <p>Not published</p>
          <p>Posted by {{ i.author }}</p>
      {% endif %}
      {% endfor %}
  </div>
{% endblock %}

blog_app/templates/blog_app/post_lists.html
{% extends 'base.html' %}
{% block content %}
  <div class="jumbotron">
      <h1><strong>Published Blogs</strong></h1>
      {% for i in post_list %}
      <!--    post_list comes from name of model in small letter + '_list'-->
      <div>
          <h1><a href="{% url 'blog_app:post_details' pk=i.pk %}">{{ i.title }}</a> </h1>
      </div>
            <p>Published on: {{ i.published_date }}</p>
            <p>Posted by <strong>{{ i.author }}</strong></p>
            <p>{{ i.comments.count }} Comments</p>
      {% endfor %}
  </div>
{% endblock %}

blog_app/templates/blog_app/post_update.html
{% extends 'base.html' %}
{% block content %}
    <div class="jumbotron">
    <h1>Update Blog</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="editable">
        {{ form.as_p }}
        </div>
        <button type="submit" class="save btn btn-primary">Update</button>
    </form>
    </div>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <!--    CSS only-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--    JS, Popper.js, and jQuery-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
<!--    Medium editor  https://github.com/yabwe/medium-editor-->
   <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<!--Custom CSS-->

    <link rel="stylesheet" type="text/css" href="{% static 'blog_app/css/master.css' %}">

    {% include 'session_security/all.html' %}
</head>
<body>

<!--<div style="background-image:  url({% static 'blog_app/images/double-bubble-dark.png' %});">-->

</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <div class="container">
    <a href="{% url 'index' %}" class="navbar-brand">Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link active" href="{% url 'blog_app:post_create' %}">Create Post</a>
            <a class="nav-item nav-link active" href="{% url 'blog_app:post_lists' %}">View Posts</a>
            <a class="nav-item nav-link active" href="{% url 'blog_app:post_drafts_list' %}">View Draft</a>
            <a class="nav-item nav-link active" href="{% url 'user_accounts_app:change_password' %}">Change Password</a>
            <a class="nav-item nav-link active" href="{% url 'user_accounts_app:signout' %}">Sign out</a>
            <p id="time_id"></p>
            {% else %}
            <a class="nav-item nav-link active" href="{% url 'user_accounts_app:signin' %}">Sign In</a>
            <a class="nav-item nav-link active" href="{% url 'user_accounts_app:signup' %}">Sign Up</a>
            <a class="nav-item nav-link active" href="{% url 'blog_app:post_lists' %}">View Posts</a>
            <p id="time_id"></p>
            {% endif %}
        </div>
    </div>
    </div>
</nav>
<div class="container mycontent">
    {% block content %}

    {% endblock %}
</div>
</body>
<!--<script src="{% static 'social_clone/js/master.js' %}"></script>-->
<script type="text/javascript" src="{% static 'blog_app/js/time.js' %}"></script>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">
    {% if user.is_authenticated %}
<h4 class="welcomeuser">Welcome {{ user }},</h4>
{% endif %}
    <h1>Publish your passions, your way</h1>
    <h2>Create a unique and beautiful blog. It’s easy and free.</h2>
{% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog_app:post_create' %}">CREATE YOUR BLOG</a>
{% else %}
     <a class="btn btn-primary" href="{% url 'user_accounts_app:signin' %}">CREATE YOUR BLOG</a>
{% endif %}
</div>


{{ auth_error }}

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
    <h1>Thank you for visiting</h1>
    </div>
{% endblock %}

templates/welcome.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome</h1>
{% endblock %}

user_accounts_app/templates/user_accounts_app/change_password.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="jumbotron">
    <h1>Change Password</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

</div>




{% endblock %}

user_accounts_app/templates/user_accounts_app/sign_in.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% load socialaccount %}
{% providers_media_js %}

{% block content %}
<div class="jumbotron">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Sign In">
         <a class="btn btn-primary" href="{% provider_login_url 'facebook' method='oauth2' %}">Sign in with Facebook</a>
        <a class="btn btn-primary" href="{% provider_login_url 'google' %}">Sign in with Google</a>
    </form>


</div>




{% endblock %}

user_accounts_app/templates/user_accounts_app/sign_up.html
{% extends 'base.html' %}
{% load bootstrap3 %}  <!--This need to install 'pip install django-bootstrap3'-->


{% load socialaccount %}
{% providers_media_js %}


{% block content %}
<div class="jumbotron">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="Sign Up">
        <a class="btn btn-primary" href="{% provider_login_url 'facebook' method='oauth2' %}">Sign in with Facebook</a>
    <a class="btn btn-primary" href="{% provider_login_url 'google' %}">Sign in with Google</a>

    </form>


</div>




{% endblock %}